version: 2
jobs:
  docker:
    environment:
      IMAGE_PATH: formio/formio-sql
    machine:
      enabled: true
      image: circleci/classic:edge
    steps:
      - run:
          name: Enable docker experimental features.
          command: |
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - attach_workspace:
          at:
            build
      - run: docker build --no-cache -t $IMAGE_PATH -f deployment/docker/Dockerfile .
      - run:
          name: deploy
          command: |
            if [[ $CIRCLE_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag $IMAGE_PATH $IMAGE_PATH:$CIRCLE_TAG
              docker push $IMAGE_PATH:$CIRCLE_TAG
              if [[ $CIRCLE_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                docker push $IMAGE_PATH
              fi
            fi

workflows:
  version: 2
  do-build:
    jobs:
      - docker:
          requires:
            - build
          filters:
            tags:
              only: /^\d+\.\d+\.\d+.*/
            branches:
              ignore: /.*/
